version: '3.9'

services:
  ht-server:
    container_name: ht-server
    build: .
    image: lucidlegend/ht-server-v1
    env_file: 
      - .env
    ports:
      - "3030:3030"
    depends_on:
      - ht-db

  ht-db:
    container_name: ht-db
    image: postgres:12
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - node_db_data:/vars/postgresql/data

volumes:
  node_db_data: {}
